============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.3.1, pluggy-1.0.0 -- /home/eren/.pyenv/versions/3.10.6/envs/taxifare-env/bin/python3.10
cachedir: .pytest_cache
rootdir: /home/eren/code/erenkiliclar/data-model-lifecycle/tests
configfile: pytest_kitt.ini
collecting ... collected 6 items / 1 error

==================================== ERRORS ====================================
__________________ ERROR collecting lifecycle/test_prefect.py __________________
ImportError while importing test module '/home/eren/code/erenkiliclar/data-model-lifecycle/tests/lifecycle/test_prefect.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../.pyenv/versions/3.10.6/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/lifecycle/test_prefect.py:6: in <module>
    from taxifare.interface.workflow import *
taxifare/interface/workflow.py:6: in <module>
    from prefect import task, flow
E   ModuleNotFoundError: No module named 'prefect'
=========================== short test summary info ============================
ERROR tests/lifecycle/test_prefect.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.89s ===============================
